header:
  heading: Fulldev UI
  variant: base
  links:
    - text: Components
      href: /introduction/
    - text: Blocks
      href: /blocks/
  search:
    icon: search
    variant: soft
  buttons:
    - href: https://github.com/fulldotdev/ui
      target: _blank
      icon: brand-github
      variant: soft
  drawer:
    - heading: Overview
      links:
        - text: Introduction
          href: /introduction/
    - heading: Structures
      folder: structures
    - heading: Components
      folder: components
    - heading: Blocks
      folder: blocks
