theme: dark
header:
  heading: Fulldev UI
  variant: base
  links:
    - text: Docs
      href: /introduction/
    - text: Components
      href: /components/base/badge
    - text: Blocks
      href: /blocks/
  search:
    icon: search
    variant: soft
  buttons:
    - href: https://github.com/fulldotdev/ui
      target: _blank
      aria-label: GitHub
      icon: brand-github
      variant: soft
  drawer:
    - heading: Overview
      links:
        - text: Introduction
          href: /introduction/
        - text: Installation
          href: /installation/
        - text: Integration
          href: /integration/
        - text: Theming
          href: /theming/
        - text: Frameworks
          href: /frameworks/
        - text: Changelog
          href: /changelog/
    - heading: Structure
      folder: components/structure
    - heading: Segment
      folder: components/segment
    - heading: Typography
      folder: components/typography
    - heading: Base
      folder: components/base
