header:
  heading: Fulldev UI
  variant: base
  links:
    - text: Docs
      href: /docs/introduction/
    - text: Components
      href: /components/
    - text: Blocks
      href: /blocks/
    - text: Structures
      href: /structures/
  buttons:
    - id: open-search
      icon: search
      variant: soft
    - href: https://github.com/fulldotdev/ui
      target: _blank
      icon: brand-github
      variant: soft
