header:
  heading: Fulldev UI
  variant: base
  links:
    - text: Docs
      href: /docs/introduction/
    - text: Components
      href: /components/
    - text: Blocks
      href: /blocks/
    - text: Structures
      href: /structures/
  search:
    icon: search
    variant: soft
  buttons:
    - href: https://github.com/fulldotdev/ui
      target: _blank
      icon: brand-github
      variant: soft
  drawer:
    - heading: Docs
      links:
        - text: Introduction
          href: /docs/introduction/
        - text: Components
          href: /docs/components/
        - text: Blocks
          href: /docs/blocks/
        - text: Structures
          href: /docs/structures/
    - heading: Components
      folder: components
    - heading: Blocks
      folder: blocks
    - heading: Structures
      folder: structures

sidebar:
  - heading: Docs
    links:
      - text: Introduction
        href: /docs/introduction/
      - text: Components
        href: /docs/components/
      - text: Blocks
        href: /docs/blocks/
      - text: Structures
        href: /docs/structures/
  - heading: Components
    folder: components
  - heading: Blocks
    folder: blocks
  - heading: Structures
    folder: structures
