spec:
  structures:
    - sections
    - section
  label: Persons

blueprint:
  impact:
  tagline:
  heading:
  text:
  buttons:
  persons:
    - name:
      tagline:
      image:

preview:
  impact: medium
  writeup: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  buttons:
    - label: Lorem ipsum
      href: '#'
    - label: Lorem ipsum
      href: '#'
  persons:
    - name: John Doe
      tagline: Lorem ipsum
      image:
        src: https://picsum.photos/seed/picsum/400/400
        alt: Lorem ipsum dolor sit
    - name: John Doe
      tagline: Lorem ipsum
      image:
        src: https://picsum.photos/seed/picsum/400/400
        alt: Lorem ipsum dolor sit
    - name: John Doe
      tagline: Lorem ipsum
      image:
        src: https://picsum.photos/seed/picsum/400/400
        alt: Lorem ipsum dolor sit