spec:
  structures:
  label: Image

blueprint:
  src:
  alt:

preview:
  src:
  alt:
  
_inputs: 
  src:
    type: image
    label: Upload
    correct_orientation: false
  alt:
    label: Description

#