body:
  - type: markdown
    attributes:
      value: |
        ## What's the context?

        What's the context for the changes? Are there any

  - type: textarea
    id: context
    attributes:
      label: "What's the context?"
      description: "What's the context for the changes? Are there any"
      placeholder: ''
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Rationale behind the change or addition

        Why did you choose to make these changes? Were there any trade-offs you had to consider?

  - type: textarea
    id: rationale
    attributes:
      label: 'Rationale behind the change or addition'
      description: 'Why did you choose to make these changes? Were there any trade-offs you had to consider?'
      placeholder: ''
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Test plan

        How do you know the changes are safe to ship to production?

  - type: textarea
    id: test-plan
    attributes:
      label: 'Test plan'
      description: 'How do you know the changes are safe to ship to production?'
      placeholder: ''
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Screenshots (optional)

        If you made visual changes, what are the before and afters?

  - type: textarea
    id: screenshots
    attributes:
      label: 'Screenshots (optional)'
      description: 'If you made visual changes, what are the before and afters?'
      placeholder: ''
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this request, you agree to follow our [Contributing Guidelines](https://github.com/fulldotdev/ui/blob/main/CONTRIBUTING.md).
      options:
        - label: My changes have been updated on the documentation if necessary
          required: false
        - label: There's no new erroneous console logs, debuggers or leftover code in my changes
          required: false
