tabWidth: 2
parser: 'typescript'
semi: false
singleQuote: true
trailingComma: 'es5'
singleAttributePerLine: true
svelteStrictMode: false
plugins:
  - 'prettier-plugin-css-order'
  - 'prettier-plugin-astro'
  - 'prettier-plugin-organize-imports' # Must be last
  - 'prettier-plugin-astro-organize-imports' # Must be last last
overrides:
  - files: '*.ts'
    options:
      parser: 'typescript'
  - files: '*.astro'
    options:
      parser: 'astro'