paths:
  data: src/data
  static: src/assets
  uploads: src/assets

# -----------------------------------------------
# Cloudcannn sidebar configuration
# -----------------------------------------------

collection_groups:
  - heading: Pages
    collections:
      - pages
      - services
      - posts
      - products
      - categories
      - policies
  - heading: Shared
    collections:
      - reviews
      - forms
      - globals
  - heading: Config
    collections:
      - settings
      - blocks

# -----------------------------------------------
# Collection configuration
# -----------------------------------------------

collections_config:
  pages:
    path: src/content/pages
    url: /[full_slug]/
    output: true
    icon: wysiwyg
    disable_add_folder: true
    _enabled_editors:
      - visual
    schemas:
      default:
        path: schemas/_pages.md

  services:
    path: src/content/services
    url: /diensten/[full_slug]/
    output: true
    icon: home_repair_service
    disable_add_folder: true
    _enabled_editors:
      - visual
    schemas:
      default:
        path: schemas/_services.md

  products:
    path: src/content/products
    url: /producten/[full_slug]/
    output: true
    icon: shopping_cart
    disable_add_folder: true
    _enabled_editors:
      - content
      - data
    schemas:
      default:
        path: schemas/_products.md

  categories:
    path: src/content/categories
    url: /categorieen/[full_slug]/
    output: true
    icon: category
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas:
      default:
        path: schemas/_categories.md

  posts:
    path: src/content/posts
    url: /posts/[full_slug]/
    output: true
    icon: edit_document
    disable_add_folder: true
    _enabled_editors:
      - content
    schemas:
      default:
        path: schemas/_posts.md

  policies:
    path: src/content/policies
    url: /beleid/[full_slug]/
    output: true
    icon: policy
    disable_add_folder: true
    _enabled_editors:
      - content
    schemas:
      default:
        path: schemas/_policies.md

  reviews:
    path: src/content/reviews
    output: false
    icon: reviews
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas:
      default:
        path: schemas/_reviews.md

  forms:
    path: src/content/forms
    output: false
    icon: dynamic_form
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas:
      default:
        path: schemas/_forms.md

  globals:
    path: src/content/globals
    output: false
    disable_file_actions: true
    disable_add_folder: true
    disable_add: true
    schemas:
      company:
        path: schemas/globals/_company.yml
      header:
        path: schemas/globals/_header.yml
      cta:
        path: schemas/globals/_cta.yml
      footer:
        path: schemas/globals/_footer.yml

  settings:
    path: src/content/settings
    output: false
    disable_file_actions: true
    disable_add_folder: true
    disable_add: true
    schemas:
      theme:
        path: schemas/settings/_theme.yml
      elements:
        path: schemas/settings/_elements.yml
      cards:
        path: schemas/settings/_cards.yml

  blocks:
    path: src/content/blocks
    url: /blocks/[full_slug]/
    output: true
    disable_add_folder: true
    _enabled_editors:
      - visual
    schemas:
      categories:
        path: schemas/blocks/_categories.yml
      contact:
        path: schemas/blocks/_contact.yml
      content:
        path: schemas/blocks/_content.yml
      cta:
        path: schemas/blocks/_cta.yml
      features:
        path: schemas/blocks/_features.yml
      hero:
        path: schemas/blocks/_hero.yml
      highlights:
        path: schemas/blocks/_highlights.yml
      intro:
        path: schemas/blocks/_intro.yml
      offers:
        path: schemas/blocks/_offers.yml
      persons:
        path: schemas/blocks/_persons.yml
      posts:
        path: schemas/blocks/_posts.yml
      products:
        path: schemas/blocks/_products.yml
      reviews:
        path: schemas/blocks/_reviews.yml
      services:
        path: schemas/blocks/_services.yml
      spotlight:
        path: schemas/blocks/_spotlight.yml

# -----------------------------------------------
# Input customization
# -----------------------------------------------

_inputs:
  text:
    type: textarea
  seo:
    label: SEO
    comment: Search engine optimization

  seo.title:
    label: Meta title
    comment: Aim for 50-60 characters

  seo.description:
    label: Meta description
    comment: Aim for 50-120 characters

  seo.image:
    label: Page image
    comment: Displayed when sharing a link to this page

  seo.noindex:
    label: Noindex
    comment: Prevent search engines from indexing this page

  seo.canonical:
    label: Canonical URL
    comment: The preferred URL for this page, meaning the url search engines will index, instead of the current one

  src:
    type: image
    label: Upload
    correct_orientation: false

  alt:
    label: Description

  href:
    type: url
    label: Link

  # -----------------------------------------------
  # Design inputs
  # -----------------------------------------------

  impact:
    type: choice
    options:
      values:
        - low
        - medium
        - high
  hue:
    type: choice
    options:
      values:
        - base
        - brand
        - accent
  scheme:
    type: choice
    options:
      values:
        - light
        - dark
  size:
    type: choice
    options:
      values:
        - small
        - medium
        - large
  layout:
    type: choice
    options:
      values:
        - col
        - row
  order:
    type: choice
    options:
      values:
        - switch
        - reverse
  image.position:
    type: choice
    options:
      values:
        - relative
        - background
        - cover
  image.ratio:
    type: choice
    options:
      values:
        - square
        - landscape
        - portrait
  class:
    type: textarea

  # -----------------------------------------------
  # Blocks collection inputs
  # -----------------------------------------------

  align:
    type: choice
    options:
      values:
        - start
        - center
        - end
  frame:
    type: choice
    options:
      values:
        - fill
        - float
        - panel
        - screen
  look:
    type: choice
    options:
      values:
        - ghost
        - outline
        - soft
        - surface
        - solid
  deck.layout:
    type: choice
    options:
      values:
        - carousel
        - grid
        - masonry
        - row
  group.importance:
    type: choice
    options:
      values:
        - primary
        - secondary
        - tertiary

  # -----------------------------------------------
  # elements to singular
  # -----------------------------------------------
  button: &singular
    type: object
  link: *singular
  image: *singular
  icon: *singular
  input: *singular
  select: *singular
  textarea: *singular
  channel: *singular
  social: *singular
  visual: *singular
  asset: *singular
  person: *singular

  writeup:
    type: html
  prose:
    type: html

  blueprint:
    hidden: true
  spec:
    hidden: true

  rating:
    type: range
    options:
      min: 0
      max: 5
      step: 0.1

  specs:
    type: array

structues:
  sections:
    style: modal

_editables:
  content:
    bold: true
    format: p h1 h2 h3 h4 h5 h6
    italic: true
    underline: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    undo: true
    redo: true
