paths:
  uploads: public/assets
  static: public

collection_groups:
  - heading: Content
    collections:
      - pages
  - heading: Data
    collections:
      - reviews
      - layouts

collections_config:
  pages:
    path: src/content/pages
    url: /[full_slug]/
    output: true
    icon: wysiwyg
    name: Pagina's
    disable_add: true
    disable_add_folder: true
    _enabled_editors:
      - content
