paths:
  data: src/data
  static: src/assets
  uploads: src/assets

# -----------------------------------------------
# Cloudcannn sidebar configuration
# -----------------------------------------------

collection_groups:
  - heading: Hebben eigen pagina
    collections:
      - pages
      - services
      - posts
      - products
      - categories
      - jobs
      - policies
  - heading: Verspreid over site
    collections:
      - reviews
      - forms
      - globals
  - heading: Eenmalig instellen
    collections:
      - settings

# -----------------------------------------------
# Collection configuration
# -----------------------------------------------

collections_config:
  pages:
    path: src/content/pages
    url: /[full_slug]/
    output: true
    icon: wysiwyg
    name: Pagina's
    disable_add_folder: true
    _enabled_editors:
      - visual
    schemas:
      default:
        path: schemas/_pages.md

  services:
    path: src/content/services
    url: /diensten/[full_slug]/
    output: true
    icon: home_repair_service
    name: Diensten
    disable_add_folder: true
    _enabled_editors:
      - visual
    schemas:
      default:
        path: schemas/_services.md

  products:
    path: src/content/products
    url: /producten/[full_slug]/
    output: true
    icon: shopping_cart
    name: Producten
    disable_add_folder: true
    _enabled_editors:
      - content
      - data
    schemas:
      default:
        path: schemas/_products.md

  categories:
    path: src/content/categories
    url: /categorieen/[full_slug]/
    output: true
    icon: category
    name: Categorieën
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas:
      default:
        path: schemas/_categories.md

  posts:
    path: src/content/posts
    url: /posts/[full_slug]/
    output: true
    icon: edit_document
    name: Post
    disable_add_folder: true
    _enabled_editors:
      - content
    schemas:
      default:
        path: schemas/_posts.md

  jobs:
    path: src/content/jobs
    url: /vacatures/[full_slug]/
    output: true
    icon: badge
    name: Vacatures
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas:
      default:
        path: schemas/_jobs.md

  policies:
    path: src/content/policies
    url: /beleid/[full_slug]/
    output: true
    icon: policy
    name: Beleid
    disable_add_folder: true
    _enabled_editors:
      - content
    schemas:
      default:
        path: schemas/_policies.md

  reviews:
    path: src/content/reviews
    output: false
    icon: reviews
    name: Review
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas:
      default:
        path: schemas/_reviews.md

  forms:
    path: src/content/forms
    output: false
    icon: dynamic_form
    name: Formulieren
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas:
      default:
        path: schemas/_forms.md

  settings:
    path: src/content/settings
    output: false
    disable_file_actions: true
    disable_add_folder: true
    disable_add: true
    icon: settings
    name: Instellingen
    schemas:
      theme:
        path: schemas/settings/_theme.yml
      elements:
        path: schemas/settings/_elements.yml
      cards:
        path: schemas/settings/_cards.yml

# -----------------------------------------------
# Input customization
# -----------------------------------------------

_inputs:
  text:
    type: textarea
    label: Tekstveld

  seo:
    label: SEO
    comment: Search engine optimization

  seo.title:
    label: Meta title
    comment: Aim for 50-60 characters

  seo.description:
    label: Meta description
    comment: Aim for 50-120 characters

  seo.image:
    label: Page image
    comment: Displayed when sharing a link to this page

  seo.noindex:
    label: Noindex
    comment: Prevent search engines from indexing this page

  seo.canonical:
    label: Canonical URL
    comment: The preferred URL for this page, meaning the url search engines will index, instead of the current one

  src:
    type: image
    label: Upload
    correct_orientation: false

  alt:
    label: Description

  href:
    type: url
    label: Link

  layout:
    hidden: true
  position:
    hidden: true
  order:
    hidden: true
  scheme:
    hidden: true
  hue:
    hidden: true
  align:
    hidden: true
  frame:
    hidden: true
  look:
    hidden: true
  scale:
    hidden: true
  render:
    hidden: true
  id:
    hidden: true
  class:
    hidden: true

  # -----------------------------------------------
  # Design inputs
  # -----------------------------------------------

  tagline:
    Label: Wenkbrauw

  heading:
    label: Koptekst

  buttons:
    label: Knoppen

  image:
    label: Afbeelding

  theme:
    label: Impact niveau
    comment: Hoe belangrijk is deze sectie voor de bezoeker?
    type: choice
    options:
      values:
        - impact-low
        - impact-medium
        - impact-high
        - impact-solid
        - impact-extreme

  # -----------------------------------------------
  # elements to singular
  # -----------------------------------------------
  prose:
    type: html

  rating:
    type: range
    options:
      min: 0
      max: 5
      step: 0.1

  specs:
    type: array

structues:
  sections:
    style: modal

_editables:
  content:
    bold: true
    format: p h1 h2 h3 h4 h5 h6
    italic: true
    underline: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    undo: true
    redo: true
