spec:
  structures:
    - sections
    - section
  label: Offer

blueprint:
  impact:
  tagline:
  heading:
  text:
  offers:
    - tagline:
      heading:
      text:
      specs:
        -
      buttons:
        - src:
          alt: