spec:
  structures:
    - sections
    - section
  label: Content

blueprint:
  impact:
  prose:
  image: 

preview:
  impact: medium
  prose: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  image:
    src: https://picsum.photos/seed/picsum/1600/900
    alt: Lorem ipsum dolor sit