spec:
  structures:
    - sections
    - section
  label: Contact

blueprint:
  impact:
  tagline:
  heading:
  text:
  channels:
  socials: 
  form:

preview:
  impact: medium
  writeup: |
    <h1>Lorem ipsum dolor sit</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  channels:
    - email
    - phone
    - whatsapp
    - address
  socials:
    - facebook
    - instagram
    - twitter
    - youtube
  form:
