spec:
  structures:
    - sections
    - section
  label: Spotlight

blueprint:
  impact:
  tagline:
  heading:
  text:
  buttons:
  image: 

preview:
  impact: medium
  writeup: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  buttons:
    - label: Lorem ipsum
      href: '#'
    - label: Lorem ipsum
      href: '#'
  image:
    src: https://picsum.photos/seed/picsum/800/600
    alt: Lorem ipsum dolor sit
