name: 'Bug report'
description: Report an issue
title: '[bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to create a bug report. Please search existing issues before submitting, as the issue may have already been addressed.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, describe how in the description.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce (optional, but very helpful if you need quick help)
      description: A step-by-step description of how to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error

  - type: textarea
    id: logs
    attributes:
      label: Logs (optional, but very helpful)
      description: 'Please include browser console and server logs around the time this bug occurred. Optional if provided reproduction. Please try not to insert an image but copy paste the log text.'
      render: bash
