blank_issues_enabled: false
contact_links:
  - name: Get Help on Discord
    url: https://discord.gg/tdmUyH2YE4
    about: If you can't get something to work, open a forum post in our Discord server.
