name: 'Feature request'
description: Create a feature request for fulldev-ui
title: '[feat]: '
labels: ['area: request']
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to create a feature request! Please search existing issues before submitting, as the issue may have already been addressed.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Tell us about your feature request
      placeholder: 'I think this feature would be nice to have because...'
      value: 'Describe your feature request...'
    validations:
      required: true

  - type: input
    id: components-affected
    attributes:
      label: Affected component/components/documentation
      description: Is this feature request relevant to any of the already existing components?
      placeholder: ex. Button, Input...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this request, you agree to follow our [Contributing Guidelines](https://github.com/fulldotdev/ui/blob/main/CONTRIBUTING.md).
      options:
        - label: I've made research efforts and searched the documentation
          required: true
        - label: I've searched for existing issues and PRs
          required: true
