spec:
  structures:
    - sections
  label: Hero
  description: Staat bovenaan de pagina en is bedoeld om de aandacht van de bezoeker te trekken.
  comment: Staat bovenaan de pagina en is bedoeld om de aandacht van de bezoeker te trekken.
  icon: preview

blueprint:
  tagline:
  heading:
  text:
  buttons:
    - label:
      href:
  image:
    position:
    ratio:
    src:
    alt: