spec:
  structures:
    - sections
    - section
  label: Highlights

blueprint:
  impact:
  highlights:
    - image:
      writeup:
      buttons:

preview:
  impact: medium
  highlights:
    - image:
        src: https://picsum.photos/seed/picsum/1600/900
        alt: Lorem ipsum dolor sit
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'
    - image:
        src: https://picsum.photos/seed/picsum/1600/900
        alt: Lorem ipsum dolor sit
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'
    - image:
        src: https://picsum.photos/seed/picsum/1600/900
        alt: Lorem ipsum dolor sit
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'