spec:
  structures:
    - sections
    - section
  label: Cta

blueprint:
  writeup:
  buttons:

preview:
  writeup: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  buttons:
    - label: Lorem ipsum
      href: '#'
    - label: Lorem ipsum
      href: '#'

config:
  section:
    frame: panel
    look: surface
    size:
    hue:
    scheme:
  segment:
    layout: col
    align: center
  group:
    layout: row
    importance: