spec:
  structures:
    - sections
    - section
  label: Reviews

blueprint:
  impact:
  tagline:
  heading:
  text:
  reviews:

preview:
  impact: medium
  writeup: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  reviews:
    - path/to/entry