spec:
  structures:
    - sections
    - section
  label: Features

blueprint:
  impact:
  tagline:
  heading:
  text:
  buttons:
  features:
    - _card_name: features
      icon:
      writeup:
      buttons:

preview:
  impact: medium
  writeup: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  buttons: 
    - label: Lorem ipsum
      href: '#'
    - label: Lorem ipsum
      href: '#'
  features:
    - icon: circle
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'
    - icon: circle
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'
    - icon: circle
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'