spec:
  structures:
    - sections
    - section
  label: Features

blueprint:
  impact:
  heading:
  text:
  buttons:
    - label:
      href:
  features:
    - tagline:
      heading:
      image:
      buttons:
        - label:
          href: