spec:
  structures:
    - sections
    - section
  label: Categories

blueprint:
  impact:
  tagline:
  heading:
  text:
  buttons:
    - label:
      href:
  categories:

preview:
  impact: medium
  writeup: |
    <h1>Lorem ipsum dolor sit</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  buttons:
    - label: Lorem ipsum
      href: '#'
    - label: Lorem ipsum
      href: '#'
  categories:
    - path/to/entry