spec:
  structures:
    - inputs
    - input
    - select
    - selects
  label: Select

blueprint:
  label:
  options:
    - ""
  required: false

preview:
  label: Lorem ipsum
  options:
    - Option 1
    - Option 2
    - Option 3
  preselect: false
  required: false

_inputs:
  options:
    type: array
#
