spec:
  structures:
    - sections
    - section
  label: Person

blueprint:
  impact:
  tagline:
  heading:
  text:
  persons:
    - tagline:
      heading:
      text:
      image:
        src:
        alt: