spec:
  structures:
    - sections
  label: Hero

blueprint:
  theme:
  tagline:
  heading:
  text:
  buttons:
  image:

preview:
  theme: impact-medium
  tagline: Lorem ipsum
  heading: Lorem ipsum dolor sit amet
  text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec.
  buttons:
    - label: Lorem ipsum
      href: '#'
    - label: Lorem ipsum
      href: '#'
  image:
    src: https://picsum.photos/seed/picsum/1600/900
    alt: Lorem ipsum dolor sit