spec:
  structures:
    - sections
    - section
  label: Posts

blueprint:
  impact:
  tagline:
  heading:
  text:
  buttons:
  posts:

preview:
  impact: medium
  writeup: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  buttons:
    - label: Lorem ipsum
      href: '#'
    - label: Lorem ipsum
      href: '#'
  posts:
    - path/to/entry