spec:
  structures:
    - inputs
    - input
  label: Input

blueprint:
  label:
  type: text
  required: false

preview:
  label: Lorem ipsum
  type: text
  required: false

_inputs:
  type:
    type: choice
    options:
      values:
        - text
        - email
        - tel
        - url
        - number
#