name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'fulldev-bot'
          git config --global user.email 'bot@full.dev'
          git remote set-url origin https://x-access-token:${{ secrets.BOT_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Fetch and Pull Latest Changes
        run: |
          git fetch origin
          git pull origin HEAD:main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Bump Version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          BRANCH_NAME="bump-version-${VERSION}"
          git checkout -b $BRANCH_NAME
          npm version $VERSION --no-git-tag-version
          git add package.json
          git commit -m "Bump to version $VERSION"
          git push origin $BRANCH_NAME

      - name: Create Pull Request and enable auto merge
        run: |
          gh pr create --base main --head $BRANCH_NAME --title "Bump version to ${VERSION}" --body "Automated version bump to ${VERSION}"
          gh pr merge --auto --merge $BRANCH_NAME
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: '2105893'
          username: 'Release Changelog'
          avatar_url: 'https://raw.githubusercontent.com/fulldotdev/ui/main/siteicon.png'
          content: 'A new release has just been published'
          footer_title: 'fulldev-ui'
          footer_icon_url: 'https://raw.githubusercontent.com/fulldotdev/ui/main/siteicon.png'
          footer_timestamp: true
